title: Just my experience...
purpose: []
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
color:
  saturation: 0.5
  brandStrength: 0.5
  rhythmicContrast: 0.9626078135333955
  brandColors:
    - '#616163'
    - '#ffffff'
    - '#8dc63f'
    - '#bbbdbe'
    - '#000000'
  lightness: 1
cta:
  bucket: null
  version: null
  domain: null
analytics:
  twitter: null
  google: null
  facebook: null
name: Mummemedia
favicon: null
opengraph:
  image: null
  type: null
  appId: null
typography_spectrum: 0.46625
layout_spectrum: 0
