name: Mummemedia
favicon: null
layout_spectrum: 1
typography_spectrum: 0.46625
title: Just my experience...
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#616163'
    - '#ffffff'
    - '#8dc63f'
    - '#bbbdbe'
    - '#000000'
  brandStrength: 0.5
  lightness: 1
  saturation: 0.5
  rhythmicContrast: 0.9626078135333955
purpose: []
